name: 02 - Workflows and Events

on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: "echo \"O evento que acionou o fluxo de trabalho foi: ${{ github.event_name }}\""

        