name: 03 - Workflow Runners

on: workflow_dispatch

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: "echo \"O trabalho está sendo executado no Ubuntu: ${{ runner.os }}\""
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              run: "echo \"O trabalho está sendo executado no Windows: ${{ runner.os }}\""
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Show OS
              run: "echo \"O trabalho está sendo executado no macOS: ${{ runner.os }}\""